### ISSUE TITLE
[bug] Doesn't automatically update when new containers are added / removed

### ISSUE THREAD

**Issue by C0DK** [pipiliang/docker-dashboard#16]
I think the title says itall - i am running current version from NPM, however when creating a new docker container i have to restart the dashboard for it to show up.

**Comment by pipiliang** [comment]
Thanks for the feedback, please update to the latest version 0.1.6.

**Comment by C0DK** [comment]
So now it removes containers that are stopped, rather than marked them as `stopped`, but otherwise it looks great :) thanks
