### ISSUE TITLE
not available for Manjaro (Archlinux)

### ISSUE THREAD

**Issue by neo5anderson** [pipiliang/docker-dashboard#8]
![uname](https://cloud.githubusercontent.com/assets/1518241/26810363/d09297f2-4a9d-11e7-8e20-d22639addf6d.png)

when I try use `docker-dashboard`

![docker-dashboard](https://cloud.githubusercontent.com/assets/1518241/26810369/dc6baa32-4a9d-11e7-85b7-055b82b11a8d.png)

**Comment by pipiliang** [comment]
I only tested on Ubuntu, and I will try to fix this problem.
